---

- name: Superfast git based search engine 
  sudo: true
  apt: pkg=silversearcher-ag state=present

- name: diffing tools
  sudo: true
  apt: pkg={{ item }} state=present
  with_items:
    - xxdiff 
    - vbindiff

